/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...other]': RouteRecordInfo<'/[...other]', '/:other(.*)', { other: ParamValue<true> }, { other: ParamValue<false> }>,
    '/about-us': RouteRecordInfo<'/about-us', '/about-us', Record<never, never>, Record<never, never>>,
    '/booknow': RouteRecordInfo<'/booknow', '/booknow', Record<never, never>, Record<never, never>>,
    '/contact-us': RouteRecordInfo<'/contact-us', '/contact-us', Record<never, never>, Record<never, never>>,
    '/deep-cleaning': RouteRecordInfo<'/deep-cleaning', '/deep-cleaning', Record<never, never>, Record<never, never>>,
    '/end-of-lease-cleaning': RouteRecordInfo<'/end-of-lease-cleaning', '/end-of-lease-cleaning', Record<never, never>, Record<never, never>>,
    '/faqs': RouteRecordInfo<'/faqs', '/faqs', Record<never, never>, Record<never, never>>,
    '/join-us': RouteRecordInfo<'/join-us', '/join-us', Record<never, never>, Record<never, never>>,
    '/our-services': RouteRecordInfo<'/our-services', '/our-services', Record<never, never>, Record<never, never>>,
    '/privacy-policy': RouteRecordInfo<'/privacy-policy', '/privacy-policy', Record<never, never>, Record<never, never>>,
    '/routine-residential-cleaning': RouteRecordInfo<'/routine-residential-cleaning', '/routine-residential-cleaning', Record<never, never>, Record<never, never>>,
    '/sign-in': RouteRecordInfo<'/sign-in', '/sign-in', Record<never, never>, Record<never, never>>,
    '/terms-and-conditions': RouteRecordInfo<'/terms-and-conditions', '/terms-and-conditions', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
  }
}
